version: '3'

services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:engineTest888@postgres:5432/zesty
      PORT: 3030
    ports:
      - '${PORT}:3030'
  postgres:
    image: mdillon/postgis:9.6
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: engineTest888
      POSTGRES_DB: zesty
    volumes:
      - ./init-db/:/docker-entrypoint-initdb.d/
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: